// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: add.proto

#include "add.pb.h"
#include "add.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace add {

static const char* Adder_method_names[] = {
  "/add.Adder/Add",
};

std::unique_ptr< Adder::Stub> Adder::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Adder::Stub> stub(new Adder::Stub(channel));
  return stub;
}

Adder::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_Add_(Adder_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Adder::Stub::Add(::grpc::ClientContext* context, const ::add::AddRequest& request, ::add::AddReply* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_Add_, context, request, response);
}

void Adder::Stub::experimental_async::Add(::grpc::ClientContext* context, const ::add::AddRequest* request, ::add::AddReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, std::move(f));
}

void Adder::Stub::experimental_async::Add(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::add::AddReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc_impl::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, std::move(f));
}

void Adder::Stub::experimental_async::Add(::grpc::ClientContext* context, const ::add::AddRequest* request, ::add::AddReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, reactor);
}

void Adder::Stub::experimental_async::Add(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::add::AddReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) {
  ::grpc_impl::internal::ClientCallbackUnaryFactory::Create(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::add::AddReply>* Adder::Stub::AsyncAddRaw(::grpc::ClientContext* context, const ::add::AddRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::add::AddReply>::Create(channel_.get(), cq, rpcmethod_Add_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::add::AddReply>* Adder::Stub::PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::add::AddRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc_impl::internal::ClientAsyncResponseReaderFactory< ::add::AddReply>::Create(channel_.get(), cq, rpcmethod_Add_, context, request, false);
}

Adder::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Adder_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Adder::Service, ::add::AddRequest, ::add::AddReply>(
          [](Adder::Service* service,
             ::grpc_impl::ServerContext* ctx,
             const ::add::AddRequest* req,
             ::add::AddReply* resp) {
               return service->Add(ctx, req, resp);
             }, this)));
}

Adder::Service::~Service() {
}

::grpc::Status Adder::Service::Add(::grpc::ServerContext* context, const ::add::AddRequest* request, ::add::AddReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace add

