// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: add.proto

#include "add.pb.h"
#include "add.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace add {

static const char* Adder_method_names[] = {
  "/add.Adder/Add",
};

std::unique_ptr< Adder::Stub> Adder::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Adder::Stub> stub(new Adder::Stub(channel, options));
  return stub;
}

Adder::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Add_(Adder_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Adder::Stub::Add(::grpc::ClientContext* context, const ::add::AddRequest& request, ::add::AddReply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::add::AddRequest, ::add::AddReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Add_, context, request, response);
}

void Adder::Stub::async::Add(::grpc::ClientContext* context, const ::add::AddRequest* request, ::add::AddReply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::add::AddRequest, ::add::AddReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, std::move(f));
}

void Adder::Stub::async::Add(::grpc::ClientContext* context, const ::add::AddRequest* request, ::add::AddReply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Add_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::add::AddReply>* Adder::Stub::PrepareAsyncAddRaw(::grpc::ClientContext* context, const ::add::AddRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::add::AddReply, ::add::AddRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Add_, context, request);
}

::grpc::ClientAsyncResponseReader< ::add::AddReply>* Adder::Stub::AsyncAddRaw(::grpc::ClientContext* context, const ::add::AddRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncAddRaw(context, request, cq);
  result->StartCall();
  return result;
}

Adder::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Adder_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Adder::Service, ::add::AddRequest, ::add::AddReply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Adder::Service* service,
             ::grpc::ServerContext* ctx,
             const ::add::AddRequest* req,
             ::add::AddReply* resp) {
               return service->Add(ctx, req, resp);
             }, this)));
}

Adder::Service::~Service() {
}

::grpc::Status Adder::Service::Add(::grpc::ServerContext* context, const ::add::AddRequest* request, ::add::AddReply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace add
#include <grpcpp/ports_undef.inc>

